platform :ios, '8.0'
 use_frameworks!

target 'Network' do
    pod 'Alamofire', '~> 4.5.0'
    pod 'HandyJSON', '~> 1.7.2'
    pod 'Moya/RxSwift'
    pod 'RxSwift', '~> 3.0'
    pod 'RxCocoa', '~> 3.0.0-beta.1'
end
